"""Persist AI trainer exercises in a markdown history file."""

from __future__ import annotations

import re
from dataclasses import dataclass
from datetime import date
from pathlib import Path

APP_DIR = Path(__file__).resolve().parent
DEFAULT_HISTORY_PATH = APP_DIR / "data" / "ai_trainer_exercises.md"

_ENTRY_HEADER_RE = re.compile(
    r"^##\s+(?P<iso_date>\d{4}-\d{2}-\d{2})\s+\|\s+(?P<title>.+)$",
    re.MULTILINE,
)
_FIELD_RE = re.compile(r"^\*\*(?P<key>[^*]+):\*\*\s*(?P<value>.+)$", re.MULTILINE)


@dataclass(frozen=True)
class ExerciseRecord:
    iso_date: str
    title: str
    exercise_id: str
    category: str
    difficulty: str
    markdown_body: str

    @property
    def summary_line(self) -> str:
        return f"{self.iso_date} | {self.category} | {self.title} ({self.difficulty})"


def history_path() -> Path:
    from os import getenv

    raw = getenv("AI_TRAINER_HISTORY_FILE", "")
    return Path(raw) if raw else DEFAULT_HISTORY_PATH


def ensure_history_file(path: Path | None = None) -> Path:
    target = path or history_path()
    target.parent.mkdir(parents=True, exist_ok=True)
    if not target.exists():
        target.write_text(
            "# AI Trainer Exercise History\n\n"
            "Daily hands-on AI exercises. New entries are appended automatically.\n",
            encoding="utf-8",
        )
    return target


def parse_exercises(text: str) -> list[ExerciseRecord]:
    records: list[ExerciseRecord] = []
    chunks = re.split(r"\n---+\n", text)
    for chunk in chunks:
        header = _ENTRY_HEADER_RE.search(chunk)
        if not header:
            continue
        fields = {m.group("key").strip().lower(): m.group("value").strip() for m in _FIELD_RE.finditer(chunk)}
        records.append(
            ExerciseRecord(
                iso_date=header.group("iso_date"),
                title=header.group("title").strip(),
                exercise_id=fields.get("id", ""),
                category=fields.get("category", ""),
                difficulty=fields.get("difficulty", ""),
                markdown_body=chunk.strip(),
            )
        )
    return records


def load_history(path: Path | None = None) -> tuple[Path, list[ExerciseRecord]]:
    target = ensure_history_file(path)
    text = target.read_text(encoding="utf-8")
    return target, parse_exercises(text)


def history_context_for_llm(records: list[ExerciseRecord], *, max_entries: int = 60) -> str:
    if not records:
        return "No prior exercises."
    recent = records[-max_entries:]
    lines = [
        "Previously assigned exercises (DO NOT repeat topics, tools, or core tasks):",
        "",
    ]
    for rec in recent:
        lines.append(f"- {rec.summary_line}")
        if rec.exercise_id:
            lines.append(f"  id: {rec.exercise_id}")
    return "\n".join(lines)


def format_exercise_markdown(
    *,
    iso_date: str,
    exercise_id: str,
    title: str,
    category: str,
    difficulty: str,
    estimated_minutes: int,
    tools: list[str],
    trend_context: str,
    exercise_steps: list[str],
    deliverable: str,
    success_criteria: list[str],
    stretch_goal: str,
    resources: list[dict[str, str]],
    skills_built: list[str],
    model_label: str,
) -> str:
    tools_line = ", ".join(tools) if tools else "—"
    resources_lines = "\n".join(
        f"- [{r.get('title', 'Link')}]({r.get('url', '#')})" for r in resources if r.get("title")
    ) or "- —"
    steps_lines = "\n".join(f"{i}. {step}" for i, step in enumerate(exercise_steps, start=1))
    criteria_lines = "\n".join(f"- {c}" for c in success_criteria)
    skills_lines = ", ".join(skills_built) if skills_built else "—"

    return f"""---

## {iso_date} | {title}

**ID:** {exercise_id}
**Category:** {category}
**Difficulty:** {difficulty}
**Estimated time:** {estimated_minutes} min
**Tools:** {tools_line}
**Generated by:** {model_label}

### Trend / Why now
{trend_context}

### Exercise
{steps_lines}

### Deliverable
{deliverable}

### Success criteria
{criteria_lines}

### Stretch goal
{stretch_goal}

### Skills built
{skills_lines}

### Resources
{resources_lines}
"""


def append_exercise(markdown_entry: str, path: Path | None = None) -> Path:
    target = ensure_history_file(path)
    text = target.read_text(encoding="utf-8").rstrip()
    entry = markdown_entry.strip()
    if not entry.startswith("---"):
        entry = f"---\n\n{entry}"
    target.write_text(f"{text}\n\n{entry}\n", encoding="utf-8")
    return target


def today_iso() -> str:
    return date.today().isoformat()


def get_record_for_date(iso_date: str, path: Path | None = None) -> ExerciseRecord | None:
    _, records = load_history(path)
    for record in reversed(records):
        if record.iso_date == iso_date:
            return record
    return None


def _markdown_section(body: str, heading: str) -> str:
    pattern = rf"### {re.escape(heading)}\s*\n(.*?)(?=\n### |\Z)"
    match = re.search(pattern, body, re.DOTALL)
    return match.group(1).strip() if match else ""


def _parse_list_lines(block: str, *, numbered: bool = False) -> list[str]:
    items: list[str] = []
    for line in block.splitlines():
        text = line.strip()
        if not text:
            continue
        if numbered:
            text = re.sub(r"^\d+\.\s*", "", text)
        else:
            text = re.sub(r"^[-*]\s*", "", text)
        if text:
            items.append(text)
    return items


def _parse_resources(block: str) -> list[dict[str, str]]:
    resources: list[dict[str, str]] = []
    for line in block.splitlines():
        match = re.match(r"^-\s+\[(?P<title>[^\]]+)\]\((?P<url>[^)]+)\)", line.strip())
        if match:
            resources.append({"title": match.group("title"), "url": match.group("url")})
    return resources


def _parse_generated_by(body: str) -> tuple[str, str]:
    fields = {m.group("key").strip().lower(): m.group("value").strip() for m in _FIELD_RE.finditer(body)}
    label = fields.get("generated by", "ChatGPT (gpt-4.1)")
    model = label
    vendor = "openai"
    if "(" in label and ")" in label:
        model = label.rsplit("(", 1)[-1].rstrip(")").strip()
    if "gemini" in label.lower():
        vendor = "gemini"
    return model, vendor

