"""Persist AI trainer exercises in a markdown history file."""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

from markdown_store import APP_DIR, append_entries, iter_entries, parse_fields, today_iso
from markdown_store import ensure_history_file as _ensure_history_file
from markdown_store import history_path as _history_path

DEFAULT_HISTORY_PATH = APP_DIR / "data" / "ai_trainer_exercises.md"
HISTORY_INTRO = (
    "# AI Trainer Exercise History\n\n"
    "Daily hands-on AI exercises. New entries are appended automatically.\n"
)

__all__ = [
    "ExerciseRecord",
    "append_exercise",
    "ensure_history_file",
    "format_exercise_markdown",
    "get_record_for_date",
    "history_context_for_llm",
    "history_path",
    "load_history",
    "parse_exercises",
    "today_iso",
]


@dataclass(frozen=True)
class ExerciseRecord:
    iso_date: str
    title: str
    exercise_id: str
    category: str
    difficulty: str
    markdown_body: str

    @property
    def summary_line(self) -> str:
        return f"{self.iso_date} | {self.category} | {self.title} ({self.difficulty})"


def history_path() -> Path:
    return _history_path("AI_TRAINER_HISTORY_FILE", DEFAULT_HISTORY_PATH)


def ensure_history_file(path: Path | None = None) -> Path:
    return _ensure_history_file(path or history_path(), HISTORY_INTRO)


def parse_exercises(text: str) -> list[ExerciseRecord]:
    records: list[ExerciseRecord] = []
    for chunk, header in iter_entries(text):
        fields = parse_fields(chunk)
        records.append(
            ExerciseRecord(
                iso_date=header.group("iso_date"),
                title=header.group("title").strip(),
                exercise_id=fields.get("id", ""),
                category=fields.get("category", ""),
                difficulty=fields.get("difficulty", ""),
                markdown_body=chunk.strip(),
            )
        )
    return records


def load_history(path: Path | None = None) -> tuple[Path, list[ExerciseRecord]]:
    target = ensure_history_file(path)
    text = target.read_text(encoding="utf-8")
    return target, parse_exercises(text)


def history_context_for_llm(records: list[ExerciseRecord], *, max_entries: int = 60) -> str:
    if not records:
        return "No prior exercises."
    recent = records[-max_entries:]
    lines = [
        "Previously assigned exercises (DO NOT repeat topics, tools, or core tasks):",
        "",
    ]
    for rec in recent:
        lines.append(f"- {rec.summary_line}")
        if rec.exercise_id:
            lines.append(f"  id: {rec.exercise_id}")
    return "\n".join(lines)


def format_exercise_markdown(
    *,
    iso_date: str,
    exercise_id: str,
    title: str,
    category: str,
    difficulty: str,
    estimated_minutes: int,
    tools: list[str],
    trend_context: str,
    exercise_steps: list[str],
    deliverable: str,
    success_criteria: list[str],
    stretch_goal: str,
    resources: list[dict[str, str]],
    skills_built: list[str],
    model_label: str,
) -> str:
    tools_line = ", ".join(tools) if tools else "—"
    resources_lines = "\n".join(
        f"- [{r.get('title', 'Link')}]({r.get('url', '#')})" for r in resources if r.get("title")
    ) or "- —"
    steps_lines = "\n".join(f"{i}. {step}" for i, step in enumerate(exercise_steps, start=1))
    criteria_lines = "\n".join(f"- {c}" for c in success_criteria)
    skills_lines = ", ".join(skills_built) if skills_built else "—"

    return f"""---

## {iso_date} | {title}

**ID:** {exercise_id}
**Category:** {category}
**Difficulty:** {difficulty}
**Estimated time:** {estimated_minutes} min
**Tools:** {tools_line}
**Generated by:** {model_label}

### Trend / Why now
{trend_context}

### Exercise
{steps_lines}

### Deliverable
{deliverable}

### Success criteria
{criteria_lines}

### Stretch goal
{stretch_goal}

### Skills built
{skills_lines}

### Resources
{resources_lines}
"""


def append_exercise(markdown_entry: str, path: Path | None = None) -> Path:
    return append_entries(ensure_history_file(path), [markdown_entry])


def get_record_for_date(iso_date: str, path: Path | None = None) -> ExerciseRecord | None:
    _, records = load_history(path)
    for record in reversed(records):
        if record.iso_date == iso_date:
            return record
    return None


def _parse_list_lines(block: str, *, numbered: bool = False) -> list[str]:
    items: list[str] = []
    for line in block.splitlines():
        text = line.strip()
        if not text:
            continue
        if numbered:
            text = re.sub(r"^\d+\.\s*", "", text)
        else:
            text = re.sub(r"^[-*]\s*", "", text)
        if text:
            items.append(text)
    return items


def _parse_resources(block: str) -> list[dict[str, str]]:
    resources: list[dict[str, str]] = []
    for line in block.splitlines():
        match = re.match(r"^-\s+\[(?P<title>[^\]]+)\]\((?P<url>[^)]+)\)", line.strip())
        if match:
            resources.append({"title": match.group("title"), "url": match.group("url")})
    return resources


def _parse_generated_by(body: str) -> tuple[str, str]:
    label = parse_fields(body).get("generated by", "ChatGPT (gpt-4.1)")
    model = label
    vendor = "openai"
    if "(" in label and ")" in label:
        model = label.rsplit("(", 1)[-1].rstrip(")").strip()
    if "gemini" in label.lower():
        vendor = "gemini"
    return model, vendor

