"""Unit tests for ai_trainer_store (exercise history markdown)."""

from __future__ import annotations

from datetime import date

import pytest

import ai_trainer_store as store

EXERCISE_ARGS = {
    "iso_date": "2026-08-10",
    "exercise_id": "ex-001",
    "title": "Build a RAG evaluation harness",
    "category": "Retrieval",
    "difficulty": "Intermediate",
    "estimated_minutes": 45,
    "tools": ["Python", "LangChain"],
    "trend_context": "Evaluation is the bottleneck for RAG systems.",
    "exercise_steps": ["Collect 20 questions", "Score answers"],
    "deliverable": "A notebook with scores.",
    "success_criteria": ["Reports recall@5"],
    "stretch_goal": "Add an LLM judge.",
    "resources": [{"title": "Docs", "url": "https://example.com"}, {"url": "https://skip.me"}],
    "skills_built": ["Evaluation"],
    "model_label": "Gemini (gemini-2.5-flash)",
}


def test_summary_line():
    record = store.ExerciseRecord(
        iso_date="2026-08-10",
        title="Build a RAG harness",
        exercise_id="ex-001",
        category="Retrieval",
        difficulty="Intermediate",
        markdown_body="",
    )
    assert record.summary_line == "2026-08-10 | Retrieval | Build a RAG harness (Intermediate)"


def test_history_path_prefers_env(monkeypatch, tmp_path):
    monkeypatch.delenv("AI_TRAINER_HISTORY_FILE", raising=False)
    assert store.history_path() == store.DEFAULT_HISTORY_PATH
    monkeypatch.setenv("AI_TRAINER_HISTORY_FILE", str(tmp_path / "hist.md"))
    assert store.history_path() == tmp_path / "hist.md"


def test_ensure_history_file_creates_and_preserves(tmp_path):
    target = tmp_path / "nested" / "hist.md"
    assert store.ensure_history_file(target) == target
    assert target.read_text(encoding="utf-8").startswith("# AI Trainer Exercise History")
    target.write_text("kept", encoding="utf-8")
    store.ensure_history_file(target)
    assert target.read_text(encoding="utf-8") == "kept"


def test_format_exercise_markdown_contains_all_sections():
    markdown = store.format_exercise_markdown(**EXERCISE_ARGS)
    assert "## 2026-08-10 | Build a RAG evaluation harness" in markdown
    assert "**ID:** ex-001" in markdown
    assert "**Tools:** Python, LangChain" in markdown
    assert "**Generated by:** Gemini (gemini-2.5-flash)" in markdown
    assert "1. Collect 20 questions" in markdown
    assert "2. Score answers" in markdown
    assert "- Reports recall@5" in markdown
    assert "- [Docs](https://example.com)" in markdown
    assert "https://skip.me" not in markdown


def test_format_exercise_markdown_placeholders_for_empty_lists():
    args = {**EXERCISE_ARGS, "tools": [], "resources": [], "skills_built": []}
    markdown = store.format_exercise_markdown(**args)
    assert "**Tools:** —" in markdown
    assert store._markdown_section(markdown, "Resources") == "- —"
    assert store._markdown_section(markdown, "Skills built") == "—"


def test_parse_exercises_round_trip():
    markdown = store.format_exercise_markdown(**EXERCISE_ARGS)
    records = store.parse_exercises(markdown)
    assert len(records) == 1
    record = records[0]
    assert record.iso_date == "2026-08-10"
    assert record.title == "Build a RAG evaluation harness"
    assert record.exercise_id == "ex-001"
    assert record.category == "Retrieval"
    assert record.difficulty == "Intermediate"


def test_parse_exercises_ignores_non_entry_chunks():
    assert store.parse_exercises("# AI Trainer Exercise History\n\nNothing yet.\n") == []


def test_append_exercise_and_load_history(tmp_path):
    target = tmp_path / "hist.md"
    store.ensure_history_file(target)
    store.append_exercise(store.format_exercise_markdown(**EXERCISE_ARGS), target)
    store.append_exercise(
        store.format_exercise_markdown(**{**EXERCISE_ARGS, "iso_date": "2026-08-11", "exercise_id": "ex-002"}),
        target,
    )
    path, records = store.load_history(target)
    assert path == target
    assert [r.exercise_id for r in records] == ["ex-001", "ex-002"]


def test_append_exercise_adds_missing_separator(tmp_path):
    target = tmp_path / "hist.md"
    store.append_exercise("## 2026-08-10 | Title\n\n**ID:** ex-001\n", target)
    text = target.read_text(encoding="utf-8")
    assert "\n---\n" in text
    assert len(store.parse_exercises(text)) == 1


def test_history_context_for_llm():
    assert store.history_context_for_llm([]) == "No prior exercises."
    records = store.parse_exercises(store.format_exercise_markdown(**EXERCISE_ARGS))
    context = store.history_context_for_llm(records)
    assert "2026-08-10 | Retrieval | Build a RAG evaluation harness (Intermediate)" in context
    assert "id: ex-001" in context


def test_history_context_for_llm_limits_entries():
    records = [
        store.ExerciseRecord(
            iso_date=f"2026-08-{day:02d}",
            title=f"Exercise {day}",
            exercise_id="",
            category="Retrieval",
            difficulty="Easy",
            markdown_body="",
        )
        for day in range(1, 11)
    ]
    context = store.history_context_for_llm(records, max_entries=2)
    assert "Exercise 10" in context
    assert "Exercise 1 " not in context


def test_today_iso():
    assert store.today_iso() == date.today().isoformat()


def test_get_record_for_date_returns_latest_match(tmp_path):
    target = tmp_path / "hist.md"
    store.append_exercise(store.format_exercise_markdown(**EXERCISE_ARGS), target)
    store.append_exercise(
        store.format_exercise_markdown(**{**EXERCISE_ARGS, "exercise_id": "ex-002"}), target
    )
    record = store.get_record_for_date("2026-08-10", target)
    assert record is not None
    assert record.exercise_id == "ex-002"
    assert store.get_record_for_date("1999-01-01", target) is None


def test_markdown_section_missing_heading():
    assert store._markdown_section("### Deliverable\nnotebook\n", "Stretch goal") == ""


def test_parse_list_lines_bulleted_and_numbered():
    assert store._parse_list_lines("- first\n* second\n\n- third") == ["first", "second", "third"]
    assert store._parse_list_lines("1. one\n2. two", numbered=True) == ["one", "two"]


def test_parse_resources_only_matches_markdown_links():
    block = "- [Docs](https://example.com)\n- plain text\n- [Guide](https://guide.dev)"
    assert store._parse_resources(block) == [
        {"title": "Docs", "url": "https://example.com"},
        {"title": "Guide", "url": "https://guide.dev"},
    ]


@pytest.mark.parametrize(
    ("label", "expected"),
    [
        ("Gemini (gemini-2.5-flash)", ("gemini-2.5-flash", "gemini")),
        ("ChatGPT (gpt-4.1)", ("gpt-4.1", "openai")),
        ("SomeModel", ("SomeModel", "openai")),
    ],
)
def test_parse_generated_by(label, expected):
    assert store._parse_generated_by(f"**Generated by:** {label}\n") == expected


def test_parse_generated_by_defaults_when_missing():
    assert store._parse_generated_by("no fields here") == ("gpt-4.1", "openai")
